In [1]:
pip install word2number


  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Created wheel for word2number: filename=word2number-1.1-py3-none-any.whl size=5589 sha256=c9c8f3cb88b84dff9ed84990332eeb559bdc25947bb7f6095d8281d7d9b52327
  Stored in directory: c:\users\samar\appdata\local\pip\cache\wheels\84\ff\26\d3cfbd971e96c5aa3737ecfced81628830d7359b55fbb8ca3b
Successfully built word2number


In [2]:
import pandas as pd
import numpy as np
from sklearn import linear_model
from word2number import w2n

In [32]:
df=pd.read_csv('hiring.csv')

In [48]:
df

experience  test  interview  salary
0           0   8.0          9   50000
1           0   8.0          6   45000
2           5   6.0          7   60000
3           2  10.0         10   65000
4           7   9.0          6   70000
5           3   7.0         10   62000
6          10   8.0          7   72000
7          11   7.0          8   80000

In [38]:
df.experience.fillna('zero',inplace=True)

In [43]:
df.rename(columns={"test_score(out of 10)":'score'},inplace=True)
df.rename(columns={df.columns[1]: 'test'}, inplace=True)  # Rename dynamically
# df.rename(columns={"per capita income (US$)": "income"}, inplace=True)
df.rename(columns={df.columns[2]: 'interview'}, inplace=True)

df.rename(columns={df.columns[3]: 'salary'}, inplace=True)

In [39]:
df['experience']=df['experience'].apply(w2n.word_to_num)
 # = df['experience'].apply(w2n.word_to_num)


In [40]:
df.experience

0     0
1     0
2     5
3     2
4     7
5     3
6    10
7    11
Name: experience, dtype: int64

In [47]:
med=df.test.median()
med
df.test.fillna(med,inplace=True)

In [49]:
reg=linear_model.LinearRegression()
reg.fit(df[['experience','test','interview']],df.salary)

LinearRegression()

In [51]:
reg.predict([[2,9,6]])

K:\anaconda\envs\py310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([53205.96797671])

In [52]:
print(reg.intercept_)
print(reg.coef_)

17737.26346433771
[2812.95487627 1845.70596798 2205.24017467]


In [53]:
import pickle

In [55]:
with open('model_pickle','wb') as f:
    pickle.dump(reg,f)
    

In [56]:
with open('model_pickle','rb') as f:
    mp=pickle.load(f)
    

In [57]:
mp.predict([[2,9,6]])

K:\anaconda\envs\py310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([53205.96797671])

In [58]:
%config Completer.use_jedi = True


In [60]:
import joblib


In [61]:
joblib.dump(reg,'model_joblib')

['model_joblib']

In [62]:
mj=joblib.load('model_joblib')
mj.predict([[2,9,6]])

K:\anaconda\envs\py310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([53205.96797671])